version: "3.3"

services:
    dovecot:
        image: dovecot/dovecot
        volumes:
            - ./docker/dovecot/volumes/dovecot.conf:/etc/dovecot/dovecot.conf:ro
            - ./docker/dovecot/volumes/passwd:/etc/dovecot/passwd:ro
        expose:
            - 12345
    amavisd:
        build:
            context: docker/amavisd/build_context
        volumes:
            - ./docker/amavisd/volumes/amavisd.conf:/etc/amavisd.conf:ro
        expose:
            - 10024
            - 10026
    log_milter:
        build:
            context: ./docker/log_milter/build_context
            args:
                PYTHON_VERSION: 3.11
        environment:
            - LOG_MILTER_SOCKET_PATH=/socket_volume/log_milter_socket
            - LOG_MILTER_TRANSCRIPT_DIRECTORY=/transcript_volume
            - LOG_MILTER_LOG_PATH=/var/log/log_milter/log_milter.log
        volumes:
            - ./docker/postfix/volumes/socket_volume:/socket_volume
            - ./docker/postfix/volumes/transcript_volume:/transcript_volume
            - ./docker/log_milter/volumes/logs:/var/log/log_milter
    opendkim:
        build:
            context: ./docker/opendkim/build_context
        volumes:
            - ./docker/opendkim/volumes/opendkim.conf:/etc/opendkim/opendkim.conf:ro
            - ./docker/opendkim/volumes/key.private:/etc/opendkim/key.private:ro
        expose:
            - 8891
    opendmarc:
        build:
            context: ./docker/opendmarc/build_context
        volumes:
            - ./docker/opendmarc/volumes/opendmarc.conf:/etc/opendmarc/opendmarc.conf
        expose:
            - 8893
    postfix:
        build:
            context: ./docker/postfix/build_context
            args:
                POSTFIX_VERSION: 3.8.0
        ports:
            - "25:25"
        volumes:
            - ./docker/postfix/volumes/master.cf:/etc/postfix/master.cf:ro
            - ./docker/postfix/volumes/main.cf:/etc/postfix/main.cf:ro
            - ./docker/postfix/volumes/submission_header_checks:/etc/postfix/submission_header_checks:ro
            - ./docker/postfix/volumes/aliases:/etc/postfix/aliases:ro
            - ./docker/postfix/volumes/fullchain.pem:/etc/postfix/fullchain.pem:ro
            - ./docker/postfix/volumes/privkey.pem:/etc/postfix/privkey.pem:ro
            - ./docker/postfix/volumes/socket_volume:/socket_volume
            - ./docker/postfix/volumes/transcript_volume:/transcript_volume
        expose:
            - 10027
        depends_on:
            - dovecot
            - amavisd
            - log_milter
            - opendkim
            - opendmarc
        restart: always
volumes:
    socket_volume: {}
    transcript_volume: {}
